### ISSUE TITLE
Auto compiler does not show help menu in Windows

### ISSUE THREAD

**Issue by KShiMin** [KShiMin/Nursery-Tic-Tac-Toe#2]
@Cyrof I am encountering issue when I type `.\compile.sh -h` command into my terminal on Visual Studio Code Window, the content of compile.sh file is shown instead of the help message shown below.

![image](https://github.com/user-attachments/assets/e1f987e0-2ddd-4446-9943-8ee305f45d0b)

**Comment by Cyrof** [comment]
Hmm seems interesting. I will try to reproduce this issue on windows.

**Comment by Cyrof** [comment]
I will be rewriting this script. So as for now use manual compilation. 
@KShiMin @yuhaolevi @yanhyee @weejerr
